In [5]:
import pandas as pd

df = pd.read_csv('combined_wine_quality.csv')
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [6]:
# New Features

# Alcohol Density
df['alcohol_density'] = df['alcohol'] * df['density']
# Sulfur Dioxide Difference
df['non-free sulfur dioxide'] = df['total sulfur dioxide'] - df['free sulfur dioxide']
# Total Acidity
df['total_acidity'] = df['fixed acidity'] + df['volatile acidity']
# Acidity Ratio
df['acidity_ratio'] = df['fixed acidity'] / df['total_acidity']
# Alcohol to pH Ratio
df['alcohol_pH_ratio'] = df['alcohol'] / df['pH']
# Alcohol to Sulfur Dioxide Ratio
df['alcohol_sulfur_dioxide_ratio'] = df['alcohol'] / df['total sulfur dioxide']

df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type,alcohol_density,non-free sulfur dioxide,total_acidity,acidity_ratio,alcohol_pH_ratio,alcohol_sulfur_dioxide_ratio
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red,9.379320,23.0,8.10,0.913580,2.678063,0.276471
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red,9.768640,42.0,8.68,0.898618,3.062500,0.146269
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red,9.770600,39.0,8.56,0.911215,3.006135,0.181481
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red,9.780400,43.0,11.48,0.975610,3.101266,0.163333
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red,9.379320,23.0,8.10,0.913580,2.678063,0.276471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white,11.100768,68.0,6.41,0.967239,3.425076,0.121739
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white,9.551040,111.0,6.92,0.953757,3.047619,0.057143
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white,9.329876,81.0,6.74,0.964392,3.143813,0.084685
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white,12.655232,90.0,5.79,0.949914,3.832335,0.116364
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white,11.675038,76.0,6.21,0.966184,3.619632,0.120408

In [7]:
# write to CSV
df.to_csv('combined_and_preprocessed_data.csv', index=False)